name: Build image and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-demo-image:${{ github.sha }}

    - name: Tag image with Registry
      run: docker tag my-demo-image:${{ github.sha }} my-registry/my-demo-image:${{ github.sha }}

    - name: Push to Registry
      run: echo "docker push my-registry/my-demo-image:${{ github.sha }}"

  scan_with_aqua_container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Aqua Container Scanner
      run: |
        docker run -v /var/run/docker.sock:/var/run/docker.sock \
        registry.aquasec.com/scanner:latest-saas scan \
        -H https://6e5d2cb597.cloud.aquasec.com \
        -A 94dd3561337f3a874bb8dd4d1a48b854ecb81f2f2316a936132efa26f658eff \
        --local myimage:latest
